import type { Composition, Product, Review } from './types'

export const COMPOSITIONS: Composition[] = [
  { id: 'linhos', name: 'Linhos' },
  { id: 'algodoes', name: 'Algodões' },
  { id: 'sedas', name: 'Sedas' },
  { id: 'aviamentos', name: 'Aviamentos' },
  { id: 'rendas', name: 'Rendas' },
  { id: 'algodao-egipcio', name: 'Algodão Egípcio' },
  { id: 'poliester', name: 'Poliéster' },
  { id: 'nylon', name: 'Nylon' },
]

export const CATEGORY_DISPLAY: Record<string, { tag: string; colors: [string, string] }> = {
  linhos: { tag: 'linho — puro', colors: ['#eee6d6', '#e0d3b6'] },
  algodoes: { tag: 'algodão — liso', colors: ['#e3ecec', '#cfe0e0'] },
  sedas: { tag: 'seda — brilho', colors: ['#efe0e6', '#e0c7d3'] },
  aviamentos: { tag: 'aviamento — misto', colors: ['#e6e4ee', '#d3cfe3'] },
  rendas: { tag: 'renda — guipure', colors: ['#f2efe8', '#e6e0d0'] },
}

export const PRODUCT_CARE_DEFAULT = 'Lavar a frio, não usar alvejante, secar à sombra.'
export const PRODUCT_DELIVERY_DEFAULT =
  'Envio em até 2 dias úteis. Corte sob medida — sem devolução após o corte.'

export const PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'LIN-BELG-001',
    slug: 'linho-belga-natural',
    name: 'Linho Belga Natural',
    categorySlug: 'linhos',
    compositions: [{ compositionId: 'linhos', percentage: 100 }],
    pricePerMeter: 128,
    widthM: 1.4,
    stockMeters: 42,
    minSaleMeters: 0.5,
    status: 'active',
    tag: 'Novo',
    colors: ['#eee6d6', '#e0d3b6'],
    description:
      'Linho belga de trama densa, ideal para estofados e cortinas de peso. Toque encorpado e caimento estruturado.',
    colorOptions: [
      { id: 'color-1-1', label: 'Natural', hex: '#e0d3b6' },
      { id: 'color-1-2', label: 'Verde Oliva', hex: '#8c9a7c' },
      { id: 'color-1-3', label: 'Azul Acinzentado', hex: '#4a5a6a' },
      { id: 'color-1-4', label: 'Índigo', hex: '#1c1a5e' },
    ],
  },
  {
    id: '2',
    sku: 'ALG-PERC-002',
    slug: 'algodao-percal-200-fios',
    name: 'Algodão Percal 200 Fios',
    categorySlug: 'algodoes',
    compositions: [{ compositionId: 'algodao-egipcio', percentage: 100 }],
    pricePerMeter: 64,
    widthM: 1.4,
    stockMeters: 8,
    minSaleMeters: 0.5,
    status: 'low_stock',
    colors: ['#e3ecec', '#cfe0e0'],
    description:
      'Percal de fio longo com maciez superior, próprio para enxovais de cama de alto padrão.',
    colorOptions: [
      { id: 'color-2-1', label: 'Azul Gelo', hex: '#cfe0e0' },
      { id: 'color-2-2', label: 'Marfim', hex: '#e8e2d4' },
      { id: 'color-2-3', label: 'Vermelho', hex: '#c13a2e' },
      { id: 'color-2-4', label: 'Marinho Escuro', hex: '#131047' },
    ],
  },
  {
    id: '3',
    sku: 'SED-CHAR-003',
    slug: 'seda-pura-charmeuse',
    name: 'Seda Pura Charmeuse',
    categorySlug: 'sedas',
    compositions: [{ compositionId: 'sedas', percentage: 100 }],
    pricePerMeter: 212,
    widthM: 1.1,
    stockMeters: 20,
    minSaleMeters: 0.5,
    status: 'active',
    tag: 'Premium',
    colors: ['#efe0e6', '#e0c7d3'],
    description:
      'Seda charmeuse com brilho acetinado e caimento fluido, indicada para peças de festa e forros nobres.',
    colorOptions: [
      { id: 'color-3-1', label: 'Rosa Antigo', hex: '#e0c7d3' },
      { id: 'color-3-2', label: 'Nude', hex: '#d4b8a0' },
      { id: 'color-3-3', label: 'Índigo', hex: '#1c1a5e' },
      { id: 'color-3-4', label: 'Marinho Escuro', hex: '#131047' },
    ],
  },
  {
    id: '4',
    sku: 'AVI-VIES-004',
    slug: 'vies-de-algodao-25mm',
    name: 'Viés de Algodão 25mm',
    categorySlug: 'aviamentos',
    compositions: [{ compositionId: 'algodoes', percentage: 100 }],
    pricePerMeter: 4.5,
    widthM: 0.025,
    stockMeters: 300,
    minSaleMeters: 0.5,
    status: 'active',
    colors: ['#e6e4ee', '#d3cfe3'],
    description:
      'Viés dobrado em algodão, disponível em diversas cores, ideal para acabamento de bordas.',
    colorOptions: [
      { id: 'color-4-1', label: 'Lavanda', hex: '#d3cfe3' },
      { id: 'color-4-2', label: 'Vermelho', hex: '#c13a2e' },
      { id: 'color-4-3', label: 'Cru', hex: '#eee6d6' },
      { id: 'color-4-4', label: 'Preto', hex: '#1a1a1a' },
    ],
  },
  {
    id: '5',
    sku: 'ALG-TRIC-005',
    slug: 'tricoline-estampada-floral',
    name: 'Tricoline Estampada Floral',
    categorySlug: 'algodoes',
    compositions: [{ compositionId: 'algodoes', percentage: 100 }],
    pricePerMeter: 38,
    widthM: 1.4,
    stockMeters: 60,
    minSaleMeters: 0.5,
    status: 'active',
    colors: ['#f0e3df', '#e3c9c0'],
    description: 'Tricoline 100% algodão com estampa floral exclusiva, leve e de fácil costura.',
    colorOptions: [
      { id: 'color-5-1', label: 'Rosa Claro', hex: '#e3c9c0' },
      { id: 'color-5-2', label: 'Verde Oliva', hex: '#8c9a7c' },
      { id: 'color-5-3', label: 'Natural', hex: '#e0d3b6' },
      { id: 'color-5-4', label: 'Marinho Escuro', hex: '#131047' },
    ],
  },
  {
    id: '6',
    sku: 'AVI-VELU-006',
    slug: 'veludo-molhado-encorpado',
    name: 'Veludo Molhado Encorpado',
    categorySlug: 'aviamentos',
    compositions: [{ compositionId: 'poliester', percentage: 100 }],
    pricePerMeter: 96,
    widthM: 1.4,
    stockMeters: 15,
    minSaleMeters: 0.5,
    status: 'active',
    tag: 'Novo',
    colors: ['#e6dde9', '#d0bcda'],
    description:
      'Veludo de toque macio e boa cobertura, excelente para estofados e almofadas decorativas.',
    colorOptions: [
      { id: 'color-6-1', label: 'Lilás', hex: '#d0bcda' },
      { id: 'color-6-2', label: 'Marinho Escuro', hex: '#131047' },
      { id: 'color-6-3', label: 'Marrom', hex: '#4a2a2a' },
      { id: 'color-6-4', label: 'Preto', hex: '#1a1a1a' },
    ],
  },
  {
    id: '7',
    sku: 'ALG-VOIL-007',
    slug: 'voil-leve-transparente',
    name: 'Voil Leve Transparente',
    categorySlug: 'algodoes',
    compositions: [{ compositionId: 'poliester', percentage: 100 }],
    pricePerMeter: 28,
    widthM: 2.8,
    stockMeters: 0,
    minSaleMeters: 0.5,
    status: 'out_of_stock',
    colors: ['#eceae2', '#dcd8c8'],
    description: 'Voil leve e transparente, indicado para cortinas e sobreposições delicadas.',
    colorOptions: [
      { id: 'color-7-1', label: 'Areia', hex: '#dcd8c8' },
      { id: 'color-7-2', label: 'Branco', hex: '#ffffff' },
      { id: 'color-7-3', label: 'Rosa Claro', hex: '#e3c9c0' },
      { id: 'color-7-4', label: 'Azul Gelo', hex: '#cfe0e0' },
    ],
  },
  {
    id: '8',
    sku: 'AVI-ZIPE-008',
    slug: 'ziper-invisivel-20cm',
    name: 'Zíper Invisível 20cm',
    categorySlug: 'aviamentos',
    compositions: [{ compositionId: 'nylon', percentage: 100 }],
    pricePerMeter: 6.9,
    widthM: 0.2,
    stockMeters: 500,
    minSaleMeters: 0.5,
    status: 'active',
    colors: ['#e4e4e4', '#d0d0d0'],
    description:
      'Zíper invisível de alta durabilidade, disponível em diversas cores para acabamento profissional.',
    colorOptions: [
      { id: 'color-8-1', label: 'Cinza', hex: '#d0d0d0' },
      { id: 'color-8-2', label: 'Preto', hex: '#1a1a1a' },
      { id: 'color-8-3', label: 'Vermelho', hex: '#c13a2e' },
      { id: 'color-8-4', label: 'Índigo', hex: '#1c1a5e' },
    ],
  },
  {
    id: '9',
    sku: 'REN-GUIP-009',
    slug: 'renda-guipure-branca',
    name: 'Renda Guipure Branca',
    categorySlug: 'rendas',
    compositions: [{ compositionId: 'poliester', percentage: 100 }],
    pricePerMeter: 84,
    widthM: 0.9,
    stockMeters: 12,
    minSaleMeters: 0.5,
    status: 'active',
    tag: 'Premium',
    colors: ['#f2efe8', '#e6e0d0'],
    description:
      'Renda guipure artesanal, delicada e resistente, perfeita para enxovais e vestidos de festa.',
    colorOptions: [
      { id: 'color-9-1', label: 'Bege', hex: '#e6e0d0' },
      { id: 'color-9-2', label: 'Cru', hex: '#eee6d6' },
      { id: 'color-9-3', label: 'Nude', hex: '#d4b8a0' },
      { id: 'color-9-4', label: 'Lilás Acinzentado', hex: '#c9c5e2' },
    ],
  },
]

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    productId: '1',
    authorName: 'Marina C.',
    rating: 5,
    text: 'Tecido encorpado, exatamente como descrito. Usei pra estofar uma poltrona e ficou lindo.',
    createdAt: '2026-06-14',
  },
  {
    id: 'r2',
    productId: '1',
    authorName: 'Roberto A.',
    rating: 4,
    text: 'Boa qualidade, só achei o prazo de entrega um pouco apertado.',
    createdAt: '2026-07-02',
  },
  {
    id: 'r3',
    productId: '3',
    authorName: 'Fernanda L.',
    rating: 5,
    text: 'Caimento perfeito para o vestido que eu queria fazer. Brilho lindo.',
    createdAt: '2026-05-20',
  },
  {
    id: 'r4',
    productId: '6',
    authorName: 'Juliana P.',
    rating: 5,
    text: 'Veludo maravilhoso, toque muito macio e cor fiel à foto.',
    createdAt: '2026-04-11',
  },
  {
    id: 'r5',
    productId: '6',
    authorName: 'Carlos E.',
    rating: 4,
    text: 'Bom custo-benefício para estofar as almofadas da sala.',
    createdAt: '2026-05-30',
  },
  {
    id: 'r6',
    productId: '6',
    authorName: 'Beatriz S.',
    rating: 3,
    text: 'Gostei da textura, mas esperava um pouco mais de cobertura de cor.',
    createdAt: '2026-06-25',
  },
  {
    id: 'r7',
    productId: '9',
    authorName: 'Helena M.',
    rating: 5,
    text: 'Renda delicada e muito bem acabada, usei no enxoval do meu bebê.',
    createdAt: '2026-07-10',
  },
]
