import type { Coupon, Delivery, DeliveryStatus, Order, OrderStatus } from './types'

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'JT-4821',
    status: 'delivered',
    paymentMethod: 'pix',
    subtotal: 404,
    shippingCost: 0,
    discountTotal: 0,
    total: 404,
    shippingAddressId: 'addr-1',
    createdAt: '2026-07-28',
    items: [
      {
        id: 'item-1-1',
        productId: '1',
        productName: 'Linho Belga Natural',
        colorId: 'color-1-2',
        colorLabel: 'Verde Oliva',
        meters: 2,
        unitPrice: 128,
        total: 256,
      },
      {
        id: 'item-1-2',
        productId: '9',
        productName: 'Renda Guipure Branca',
        colorId: 'color-9-1',
        colorLabel: 'Bege',
        meters: 1,
        unitPrice: 84,
        total: 84,
      },
      {
        id: 'item-1-3',
        productId: '2',
        productName: 'Algodão Percal 200 Fios',
        colorId: 'color-2-2',
        colorLabel: 'Marfim',
        meters: 1,
        unitPrice: 64,
        total: 64,
      },
    ],
  },
  {
    id: 'order-2',
    orderNumber: 'JT-4756',
    status: 'shipping',
    paymentMethod: 'boleto',
    subtotal: 106,
    shippingCost: 25,
    discountTotal: 0,
    total: 131,
    shippingAddressId: 'addr-1',
    createdAt: '2026-07-14',
    items: [
      {
        id: 'item-2-1',
        productId: '3',
        productName: 'Seda Pura Charmeuse',
        colorId: 'color-3-1',
        colorLabel: 'Rosa Antigo',
        meters: 0.5,
        unitPrice: 212,
        total: 106,
      },
    ],
  },
  {
    id: 'order-3',
    orderNumber: 'JT-4602',
    status: 'delivered',
    paymentMethod: 'credit_card',
    subtotal: 210,
    shippingCost: 25,
    discountTotal: 0,
    total: 235,
    shippingAddressId: 'addr-2',
    createdAt: '2026-06-02',
    items: [
      {
        id: 'item-3-1',
        productId: '5',
        productName: 'Tricoline Estampada Floral',
        colorId: 'color-5-1',
        colorLabel: 'Rosa Claro',
        meters: 3,
        unitPrice: 38,
        total: 114,
      },
      {
        id: 'item-3-2',
        productId: '6',
        productName: 'Veludo Molhado Encorpado',
        colorId: 'color-6-2',
        colorLabel: 'Marinho Escuro',
        meters: 1,
        unitPrice: 96,
        total: 96,
      },
    ],
  },
  {
    id: 'order-4',
    orderNumber: 'JT-4487',
    status: 'paid',
    paymentMethod: 'pix',
    subtotal: 499.8,
    shippingCost: 0,
    discountTotal: 0,
    total: 499.8,
    shippingAddressId: 'addr-1',
    createdAt: '2026-05-19',
    items: [
      {
        id: 'item-4-1',
        productId: '1',
        productName: 'Linho Belga Natural',
        colorId: 'color-1-1',
        colorLabel: 'Natural',
        meters: 3,
        unitPrice: 128,
        total: 384,
      },
      {
        id: 'item-4-2',
        productId: '8',
        productName: 'Zíper Invisível 20cm',
        colorId: 'color-8-2',
        colorLabel: 'Preto',
        meters: 2,
        unitPrice: 6.9,
        total: 13.8,
      },
      {
        id: 'item-4-3',
        productId: '4',
        productName: 'Viés de Algodão 25mm',
        colorId: 'color-4-3',
        colorLabel: 'Cru',
        meters: 4,
        unitPrice: 4.5,
        total: 18,
      },
      {
        id: 'item-4-4',
        productId: '9',
        productName: 'Renda Guipure Branca',
        colorId: 'color-9-3',
        colorLabel: 'Nude',
        meters: 1,
        unitPrice: 84,
        total: 84,
      },
    ],
  },
]

export const MOCK_DELIVERIES: Delivery[] = [
  {
    id: 'delivery-1',
    orderId: 'order-1',
    carrier: 'Correios',
    trackingCode: 'BR123456789JM',
    status: 'delivered',
    etaDate: '2026-08-02',
  },
  {
    id: 'delivery-2',
    orderId: 'order-2',
    carrier: 'Jadlog',
    trackingCode: 'JD987654321BR',
    status: 'in_transit',
    etaDate: '2026-07-20',
  },
  {
    id: 'delivery-3',
    orderId: 'order-3',
    carrier: 'Correios',
    trackingCode: 'BR555666777JM',
    status: 'delivered',
    etaDate: '2026-06-08',
  },
  {
    id: 'delivery-4',
    orderId: 'order-4',
    carrier: 'Correios',
    trackingCode: 'BR111222333JM',
    status: 'awaiting_pickup',
    etaDate: '2026-05-27',
  },
]

export const COUPONS: Coupon[] = [
  { id: 'coupon-1', code: 'BEMVINDO10', type: 'percentage', value: 10, usedCount: 34, status: 'active' },
  { id: 'coupon-2', code: 'FRETEGRATIS', type: 'free_shipping', value: 0, usedCount: 12, status: 'active' },
  {
    id: 'coupon-3',
    code: 'PROMOJULHO',
    type: 'fixed',
    value: 20,
    maxUses: 50,
    usedCount: 50,
    expiresAt: '2026-07-31',
    status: 'expired',
  },
]

export const ORDER_STATUS_LABELS: Record<OrderStatus, string> = {
  pending: 'Aguardando pagamento',
  paid: 'Em preparação',
  shipping: 'Enviado',
  delivered: 'Entregue',
  cancelled: 'Cancelado',
}

export const ORDER_STATUS_STYLES: Record<OrderStatus, string> = {
  pending: 'bg-[#f2ede4] text-[#8c8375]',
  paid: 'bg-[#f2ede4] text-[#8c8375]',
  shipping: 'bg-[#e6e4ee] text-[#1c1a5e]',
  delivered: 'bg-[#e3ecec] text-[#2f6b5e]',
  cancelled: 'bg-[#f2e4e4] text-[#8c3d3d]',
}

export const DELIVERY_STATUS_LABELS: Record<DeliveryStatus, string> = {
  awaiting_pickup: 'Aguardando coleta',
  in_transit: 'A caminho',
  delivered: 'Entregue',
  delayed: 'Atrasado',
}
